# Generated by Django 4.1.7 on 2023-04-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modules_status_alter_sections_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('document_number', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staticcountries', verbose_name='country relation')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staticdocumenttypes', verbose_name='document type relation')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personals', verbose_name='personal relation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles', verbose_name='role relation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
