# Generated by Django 4.1.7 on 2023-04-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='personal',
            new_name='personal_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='role_id',
        ),
    ]
